#pragma once
#include <vector>
#include <string>
#include <cstdint>
#include <unordered_map>

namespace guardian::vm {

// ── Code Generator ──
class CodeGen {
public:
    CodeGen();
    
    // Emit instructions
    void emit(uint8_t opcode);
    void emit(uint8_t opcode, uint32_t operand);
    void emitString(const std::string& str);
    
    // Variable management
    uint32_t declareVariable(const std::string& name);
    uint32_t getVariableIndex(const std::string& name) const;
    void storeVariable(uint32_t index);
    void loadVariable(uint32_t index);
    
    // Print operations
    void print();
    void println();
    void space();
    void newline();
    
    // Constants
    void pushInt(int32_t value);
    void pushFloat(double value);
    void pushBool(bool value);
    void pushString(const std::string& value);
    void pushNull();
    
    // Control flow
    void halt();
    void jump(uint32_t address);
    void jumpIf(uint32_t address);
    void jumpIfNot(uint32_t address);
    
    // Get the generated bytecode
    std::vector<uint8_t> getBytecode() const;
    
    // Debug
    void dump() const;
    
private:
    std::vector<uint8_t> bytecode;
    std::unordered_map<std::string, uint32_t> variableMap;
    std::unordered_map<uint32_t, std::string> stringTable;
    uint32_t nextVariableIndex = 0;
    uint32_t nextStringIndex = 0;
    
    void emitUint32(uint32_t value);
};

} // namespace guardian::vm
